version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Rootkali123"
      MYSQL_DATABASE: "algafood"
      TZ: "UTC"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
