insert into tab_cozinha (col_nome) values ('Tailandesa');
insert into tab_cozinha (col_nome) values ('Brasileira');
insert into tab_cozinha (col_nome) values ('Italiana');
insert into tab_cozinha (col_nome) values ('Mexicana');
insert into tab_cozinha (col_nome) values ('Indiana');
insert into tab_cozinha (col_nome) values ('Chinesa');
insert into tab_cozinha (col_nome) values ('Japonesa');
insert into tab_cozinha (col_nome) values ('Francesa');
insert into tab_cozinha (col_nome) values ('Espanhola');
insert into tab_cozinha (col_nome) values ('Alemã');
insert into tab_cozinha (col_nome) values ('Grega');
insert into tab_cozinha (col_nome) values ('Coreana');
insert into tab_cozinha (col_nome) values ('Turca');
insert into tab_cozinha (col_nome) values ('Portuguesa');
insert into tab_cozinha (col_nome) values ('Árabe');
insert into tab_cozinha (col_nome) values ('Russa');
insert into tab_cozinha (col_nome) values ('Sueca');
insert into tab_cozinha (col_nome) values ('Polonesa');
insert into tab_cozinha (col_nome) values ('Argentina');
insert into tab_cozinha (col_nome) values ('Peruana');
insert into tab_cozinha (col_nome) values ('Colombiana');
insert into tab_cozinha (col_nome) values ('Venezuelana');
insert into tab_cozinha (col_nome) values ('Marroquina');
insert into tab_cozinha (col_nome) values ('Norueguesa');
insert into tab_cozinha (col_nome) values ('Finlandesa');
insert into tab_cozinha (col_nome) values ('Suíça');
insert into tab_cozinha (col_nome) values ('Canadense');
insert into tab_cozinha (col_nome) values ('Cubana');
insert into tab_cozinha (col_nome) values ('Angolana');
insert into tab_cozinha (col_nome) values ('Moçambicana');
insert into tab_cozinha (col_nome) values ('Nigeriana');
insert into tab_cozinha (col_nome) values ('Sul-Africana');
insert into tab_cozinha (col_nome) values ('Australiana');
insert into tab_cozinha (col_nome) values ('Neozelandesa');
insert into tab_cozinha (col_nome) values ('Havaiana');
insert into tab_cozinha (col_nome) values ('Cajun');
insert into tab_cozinha (col_nome) values ('Caribenha');
insert into tab_cozinha (col_nome) values ('Mediterrânea');
insert into tab_cozinha (col_nome) values ('Nórdica');
insert into tab_cozinha (col_nome) values ('Pakistã');
insert into tab_cozinha (col_nome) values ('Filipina');
insert into tab_cozinha (col_nome) values ('Vietnamita');
insert into tab_cozinha (col_nome) values ('Húngara');
insert into tab_cozinha (col_nome) values ('Indonésia');
insert into tab_cozinha (col_nome) values ('Belga');
insert into tab_cozinha (col_nome) values ('Austriaca');
insert into tab_cozinha (col_nome) values ('Irlandesa');
insert into tab_form_pagamento (descricao) values ('Crédito');
insert into tab_form_pagamento (descricao) values ('Débito');
insert into tab_form_pagamento (descricao) values ('Pix');
insert into estado (nome) values ('Santa Catarina');
insert into estado (nome) values ('Rio Grande do Sul');
insert into estado (nome) values ('Paraná');
insert into cidade (nome, estado_id) values ('Joinville', 1);
insert into cidade (nome, estado_id) values ('BLumenau', 1);
insert into cidade (nome, estado_id) values ('Cascavel', 3);
insert into cidade (nome, estado_id) values ('Canela', 2);
insert into permissao (nome, descricao) values ('Administrador', 'Usuario com permissão total.');
insert into permissao (nome, descricao) values ('Usuario', 'Usuario com permissão para interessão apenas.');
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Restaurante Alegria Tranquila', 3.50, 1,1);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Cantinho da Paz', 2.80, 3,2);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Sabor Sereno', 4.10, 3,1);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Gastronomia Zen', 3.20, 6,2);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Refeições Relaxantes', 2.50,6,1);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Bistrô Harmonia', 3.80,1,1);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Sabores Suaves', 2.90,2,1);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Delícias Despreocupadas', 3.60,8,2);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Cozinha Calma', 3.30,9,3);
INSERT INTO tab_restaurante (nome, taxa_frete, cozinha_codigo,forma_pagamento_id) VALUES ('Ristorante Tranquilidade', 2.70,7,3);